name: Deploy docker container

on:
  workflow_dispatch:

env:
  IMAGE_NAME: greenhouse

jobs:
  add_build_version:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
          
      - name: Install GitVersion
        uses: gittools/actions/gitversion/setup@v3.1.1
        with:
          versionSpec: '6.0.x'     

      - name: Determine Version
        id: version_step
        uses: gittools/actions/gitversion/execute@v3.1.1
  
  build_and_deploy_docker_container:
    runs-on: ubuntu-latest
    steps:
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      
      - name: Login to Container Registry
        uses: docker/login-action@v3
        with:
          registry: greenhouseregistry.azurecr.io
          username: greenhouseRegistry
          password: ${{ secrets.AZ_CONTAINER_REGISTRY_TOKEN }}
      
      - name: Build and push
        uses: docker/build-push-action@v6
        with:
          platforms: linux/amd64
          push: true
          file: ./Dockerfile
          tags: |
            prpucontainerregistry.azurecr.io/${{ env.IMAGE_NAME }}:${{ github.sha }}
      # - name: 'Login via Azure CLI'
      #   uses: azure/login@v1
      #     with:
      #       creds: ${{ secrets.AZURE_CREDENTIALS }}
   
      # - name: 'Deploy to Azure Container Instances'
      #   uses: 'azure/aci-deploy@v1'
      #   with:
      #     resource-group: ${{ secrets.RESOURCE_GROUP }}
      #     dns-name-label: ${{ secrets.RESOURCE_GROUP }}${{ github.run_number }}
      #     image: ${{ secrets.REGISTRY_LOGIN_SERVER }}/sampleapp:${{ github.sha }}
      #     registry-login-server: ${{ secrets.REGISTRY_LOGIN_SERVER }}
      #     registry-username: ${{ secrets.REGISTRY_USERNAME }}
      #     registry-password: ${{ secrets.REGISTRY_PASSWORD }}
      #     name: aci-sampleapp
      #     location: 'west us'
